## 00. Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.9.0+cpu


In [ ]:
#!nvidia-smi

## Introduction to Tensor

### Creating tensors

Pytorch tensors are created using **torch.Tensor()**

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([
    [7,8],
    [9,10]
])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
  MATRIX[0]

tensor([7, 8])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
    [3,6,9],
    [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
# Tensor
TENSOR2 = torch.tensor([[[[1,2,3,4],
    [3,6,9,10],
    [2,4,5,7],
    [10,11,12,13]]]])
TENSOR2

tensor([[[[ 1,  2,  3,  4],
          [ 3,  6,  9, 10],
          [ 2,  4,  5,  7],
          [10, 11, 12, 13]]]])

In [ ]:
TENSOR2.shape

torch.Size([1, 1, 4, 4])

In [ ]:
TENSOR2.ndim

4

### Random Tensors

Why random tensors ?

Random tensors are important because the way neural networks learn is that they start with tensors full of random numbers, and adjust those random numbers to better represent data

Start with random numbers -> look at data -> update randomnumbers -> look at data -> update

In [ ]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6221, 0.3060, 0.6727, 0.3467],
        [0.0458, 0.0080, 0.4130, 0.9041],
        [0.7060, 0.5081, 0.9977, 0.4376]])

In [ ]:
# Create a random tensoir with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))# height, width, coluor channels (R, G, B)
random_image_size_tensor.ndim

3

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
# default data type
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.arange() / range is deprecated
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros =  torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_ones = torch.ones_like(input=one_to_ten)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes

**Note**: Tensor datatypes is one the 3 big errors you'll run into with PyTrch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not the right device

In [ ]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # Datatype of the tensor(ex: float32, float16...)
                               device=None, # CPU or GPU
                               requires_grad=False # whether or not to track gradients
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
# Change datatype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

### Gettings informations from tensors (tensors attributes)
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to do get the shape from a tensor, can use `tensor.shape`
3. Tensors not the right device - to do get the device from a tensor, can use `tensor.device`

In [ ]:
some_tensor = torch.rand((3,4))
some_tensor

tensor([[0.4103, 0.4546, 0.6623, 0.6722],
        [0.7500, 0.2716, 0.6851, 0.5920],
        [0.8973, 0.6133, 0.3661, 0.6459]])

In [ ]:

print(some_tensor)
print(f"Data of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.4103, 0.4546, 0.6623, 0.6722],
        [0.7500, 0.2716, 0.6851, 0.5920],
        [0.8973, 0.6133, 0.3661, 0.6459]])
Data of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensors operations)

Tensors operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrice multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor =  torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Substract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix multiplication
There are two ways of performing  multiplication in neurla networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisty:
1. The **inner dimensions** must match


*   (3,2) @ (3,2) won't work
*   (2,3) @ (3,2) will work
*   (3,2) @ (2,3) will work

2. The resulting matrix has the shape of the **outer dimensions**
*   (2,3) @ (3,2) -> (2,2)
*   (3,2) @ (2,3) -> (3,3)


In [ ]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
# matrix multiplication by hand
multi = 0
for i in range(len(tensor)):
  multi += tensor[i]*tensor[i]
print(multi)

tensor(14)


In [ ]:
# Matrice multplication
matrice1 = torch.tensor([[1,2,3],[4,5,6]])
matrice2 = torch.tensor([[7,8,9],[10,11,12],[13,14,15]])

print(matrice1)
print(matrice2)
print(f"Shape of matrice 1: {matrice1.shape}")
print(f"Shape of matrice 2: {matrice2.shape}")


torch.matmul(matrice1, matrice2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])
Shape of matrice 1: torch.Size([2, 3])
Shape of matrice 2: torch.Size([3, 3])


tensor([[ 66,  72,  78],
        [156, 171, 186]])

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensoir shape issue, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# Matrix multiplication operation works when tensor_B is transposed

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")

torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0,100,10)

In [ ]:
# find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensoir of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [ ]:
# Find the position of max, min, to find it we use the function argmax, argmin
torch.argmax(x), torch.argmin(x)

(tensor(9), tensor(0))

### Reshapping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view of an input tensor of certain shape but keep the memory same as the original tensor
* Stacking - combine multiple tensors on top of each others (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with the dimensions permuted (swapped) in a certain way

In [ ]:
import torch

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
## Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Change the viex
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# Changing z changes x (because a view of tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top on each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
# torch.Squeeze() - remove all single dimension
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remvove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"New tensor: {x_squeezed}")
print(f"Nex shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])
New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Nex shape: torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific domension

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Remvove extra dimensions from x_reshaped
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New tensor: {x_unsqueezed}")
print(f"Nex shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])
New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Nex shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permuted the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][1]

tensor(2)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

### Pytorch tensors & NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
 # NumPy array to tensor
 import torch
 import numpy as np

 array = np.arange(1.0, 8.0)
 tensor = torch.from_numpy(array)
 array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Chnage the value of array, what will this do to `tensor`?

array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# Chnage the value of array, what will this do to `tensor`?

tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)

In short how a neural network learns:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> agin -> agin...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random sedd**.
Essentially what the random seed does is "flavour" the randomness

In [ ]:
import torch
# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9709, 0.7641, 0.2922, 0.2538],
        [0.5416, 0.1269, 0.1036, 0.6487],
        [0.3726, 0.1949, 0.7126, 0.6339]])
tensor([[0.3057, 0.2697, 0.7522, 0.0739],
        [0.8183, 0.7820, 0.6715, 0.6147],
        [0.8625, 0.9821, 0.8481, 0.8190]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducbility tensors

import torch


RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (and making fasters computation)

In [ ]:
!nvidia-smi

Fri Jan 30 14:58:04 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   45C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

#### 1. Check for GPU access with PyTorch

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# Count the numbers of devices
torch.cuda.device_count()

1

#### 2. Putting tensors (and models) on the GPU

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

#### 3. Moving tensors back to the CPU

In [ ]:
# if tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_on_cpu =  tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu, tensor_back_on_cpu.device

(array([1, 2, 3]), 'cpu')

In [ ]:
tensor_on_gpu.device

device(type='cuda', index=0)

### Exercices & Extra-curriculum

#### 2. Create a random tensor with shape (7,7)

In [ ]:
import torch
random_tensor = torch.rand(7,7)
random_tensor

tensor([[6.1920e-01, 9.6219e-01, 3.6107e-01, 1.8977e-02, 2.6057e-01, 3.9064e-02,
         2.1386e-01],
        [3.4073e-02, 5.8919e-01, 1.6087e-04, 1.8789e-01, 1.8123e-01, 5.7741e-01,
         4.5699e-01],
        [5.6330e-01, 8.8088e-02, 4.9422e-01, 2.0179e-01, 7.6725e-01, 8.7418e-01,
         9.3575e-01],
        [9.9267e-01, 1.8204e-01, 7.2181e-01, 1.0367e-01, 3.7714e-01, 8.0794e-01,
         1.1393e-01],
        [7.2057e-01, 5.1255e-01, 4.6976e-01, 8.7428e-01, 6.1012e-02, 8.5697e-01,
         6.1588e-01],
        [9.2953e-01, 4.4955e-01, 6.1755e-01, 7.3410e-01, 9.3090e-01, 4.6592e-01,
         3.8340e-01],
        [3.2839e-01, 5.1595e-01, 1.3402e-01, 4.4802e-01, 3.9640e-01, 4.0036e-01,
         6.5422e-01]])

#### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
another_random_tensor = torch.rand(1,7)

# Create matrix multiplication
torch.matmul(random_tensor, another_random_tensor.T)

tensor([[1.1316],
        [1.0929],
        [1.6510],
        [1.6687],
        [1.9952],
        [1.8671],
        [1.2375]])

#### 4. Set the random seed to 0 and do 2 & 3 over again.

In [ ]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
# Create two random tensors
random_tensor_1 = torch.rand(7,1)
random_tensor_2 = torch.rand(7,1)
# Matrix multiply tensors
torch.matmul(random_tensor_1, random_tensor_2.T)


tensor([[0.4449, 0.2261, 0.3138, 0.1731, 0.1994, 0.0111, 0.0838],
        [0.6887, 0.3500, 0.4858, 0.2680, 0.3086, 0.0172, 0.1297],
        [0.0793, 0.0403, 0.0559, 0.0309, 0.0355, 0.0020, 0.0149],
        [0.1184, 0.0602, 0.0835, 0.0461, 0.0530, 0.0029, 0.0223],
        [0.2756, 0.1401, 0.1944, 0.1073, 0.1235, 0.0069, 0.0519],
        [0.5684, 0.2889, 0.4009, 0.2212, 0.2547, 0.0142, 0.1071],
        [0.4393, 0.2233, 0.3099, 0.1710, 0.1969, 0.0109, 0.0828]])

#### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [ ]:
# Set random
torch.cuda.manual_seed(1234)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
# Create two random tensors on GPU
random_tensor_on_gpu_1 = torch.rand(2,3).to(device)
random_tensor_on_gpu_2 = torch.rand(2,3).to(device)

#### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [ ]:
output_tensor = torch.matmul(random_tensor_on_gpu_1, random_tensor_on_gpu_2.T)
output_tensor

tensor([[0.9519, 0.8601],
        [0.8048, 0.9229]])

#### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
max = torch.max(output_tensor)
# Find min
min = torch.min(output_tensor)
max, min

(tensor(0.9519), tensor(0.8048))

#### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find the arg max
index_max = torch.argmax(output_tensor)
# Find the arg min
index_min = torch.argmin(output_tensor)

index_max, index_min

(tensor(0), tensor(2))

#### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [ ]:
torch.cuda.manual_seed(7)

random_tensor = torch.rand(1,1,1,10)
squeezed_random_tensor = torch.squeeze(random_tensor)

print(f"First Tensor: {random_tensor} {random_tensor.shape}")
print(f"Second Tensor: {squeezed_random_tensor} {squeezed_random_tensor.shape}")

First Tensor: tensor([[[[0.4177, 0.2711, 0.6923, 0.2038, 0.6833, 0.7529, 0.8579, 0.6870,
           0.0051, 0.1757]]]]) torch.Size([1, 1, 1, 10])
Second Tensor: tensor([0.4177, 0.2711, 0.6923, 0.2038, 0.6833, 0.7529, 0.8579, 0.6870, 0.0051,
        0.1757]) torch.Size([10])
